---
- name: Join k8s nodes to cluster
  hosts: k8s09.breeze-blocks.net
  become: true
  roles:
    - role: edwardtheharris.k8s.reset
      tags:
        - reset
    - role: edwardtheharris.k8s.join
      tags:
        - join
    - role: edwardtheharris.k8s.glances
      tags:
        - glances
