---
- name: Join k8s nodes to cluster
  hosts: k8s09.breeze-blocks.net
  become: true
  roles:
    - role: reset
      tags:
        - reset
    - role: join
      tags:
        - join
    - role: glances
      tags:
        - glances
