---
- name: Add some programs
  community.general.pacman:
    name: "{{ item }}"
    executable: yay
  loop:
    - kubeadm
    - kubelet
  become: true
  become_user: duchess
- name: Reset existing nodes
  ansible.builtin.shell:
    cmd: kubeadm reset -f
  register: reset_result
- name: Show reset results
  ansible.builtin.debug:
    var: reset_result.stdout
- name: Enable kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted
    enabled: true
- name: Delete nodes from cluster
  ansible.builtin.shell:
    cmd: "kubectl delete nodes {{ inventory_hostname }} || true"
  delegate_to: kcp01
