---
- name: Prepare
  hosts: local
  gather_facts: false
  vars:
    molecule_inventory:
      all:
        hosts: {}
        molecule:
          molecule-arch:
            ansible_user: duchess
  tasks:
    - name: Ensure python
      community.general.pacman:
        name: python
        state: present
        update_cache: true
      become: true
